### ISSUE TITLE
Cannot read property 'settings' of undefined

### ISSUE THREAD

**Issue by iamdubx** [egoist/v-tippy#1]
I got this error, when I try to use html element

```
Uncaught TypeError: Cannot read property 'settings' of undefined
    at HTMLDocument.clickHandler
```
My code is 
```
<button
      title="I'm on the left!"
      v-tippy="{html: '#my'}">
      hover me
    </button>
    <div id="my" style="display: none;">
      <p>Fun <strong>non-interactive HTML</strong> here</p>
      <img alt="cat" height="150" src="img/cat.jpg">
    </div>
```
Any tips how to handle it?
Also I need to mention, that error appears not everytime, sometimes I need to refresh page to get this error, in other case it just works.

Also I am wonder how to use my own component in tooltip?

**Comment by egoist** [comment]
Try `v1.0.1` hopefully it fixed this.

And you can't use Vue component in the tooltip, cuz tippy does not natively support that.

**Comment by iamdubx** [comment]
Great, it works. Thanks for update!
